name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Generate the Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: dexxxxca
          outputs: dist/github-contribution-grid-snake-dark.svg

      - name: Push Snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
